spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: productos-sv
          uri: lb://productos-sv
          predicates:
            - Path=/product/**
        - id: pagos-sv
          uri: lb://pagos-sv
          predicates:
            - Path=/pago/**
            - Path=/webhook/**
        - id: pedidos-sv
          uri: lb://pedidos-sv
          predicates:
            - Path=/pedido/**
        - id: usuarios-sv
          uri: lb://usuarios-sv
          predicates:
            - Path=/users/**
            - Path=/auth/**
            - Path=/permission/**
            - Path=/role/**
        - id: notificaciones-sv
          uri: lb://notificaciones-sv
          predicates:
            - Path=/mail/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.server: DEBUG
