spring:
  application:
    name: notificaciones-sv
email:
  sender: ${email}
  password: ${password}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:${SERVER_PORT:0}}