spring:
  application:
    name: pedidos-sv
server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pedido_db?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

security:
  jwt:
    private:
      key: ${PRIVATE_KEY}
    user:
      generator: ${GENERATOR}

resilience4j:
  circuitbreaker:
    configs:
      shared:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      emailCB:
        baseConfig: shared
      pagoCB:
        baseConfig: shared
      productoCB:
        baseConfig: shared
