server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/francodavyd/Microservicios-Docker-SpringSecurity
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASS}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  application:
    name: config-server